kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: generator-dev
spec:
  serviceName: generator-dev
  replicas: 1
  template:
    metadata:
      labels:
        spark-role: app
    spec:
      volumes:
        - name: spark-conf
          configMap:
            name: generator-dev-config
            items:
              - key: spark-env.sh
                path: spark-env.sh
              - key: spark-defaults.conf
                path: spark-defaults.conf
      containers:
        - name: generator-dev
          image: databench/apache-spark-basic
          command: 
            - sleep
            - 120d
          envFrom:
            - configMapRef:
                name: databench-env
            - configMapRef:
                name: spark-env
          volumeMounts:
            - name: spark-conf
              mountPath: "/usr/share/apache-spark/conf"
              
          
