kind: Service
apiVersion: v1
metadata:
  name: spark
spec:
  selector:
    role: spark-master
  clusterIP: None
  ports:
    - protocol: TCP
      name: webui
      port: 8080
    - protocol: TCP
      name: spark
      port: 7077
#  type: NodePort
