kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-master-controller
  namespace: spark
spec:
  replicas: 1
  selector:
    component: spark-master
  template:
    metadata:
      labels:
        component: spark-master
    spec:
      nodeSelector:
        use: spark-master
      containers:
        - name: spark-master
          image: docker.io/eoshaugh/spark-master
          ports:
            - containerPort: 7077
            - containerPort: 8080
