apiVersion: v1
kind: ConfigMap
metadata:
  name: spark-master-config
  namespace: default
data:
  spark-env.sh: |
    SPARK_NO_DAEMONIZE=1
    export PYSPARK_PYTHON=/usr/bin/python3
    export PYSPARK_DRIVER_PYTHON=/usr/bin/ipython
  spark-defaults.conf: |
    # spark.master
    # spark.eventLog.enabled
    # spark.eventLog.dir
    # spark.serializer
    # spark.driver.memory
    # spark.executor.extraJavaOptions
    
    
