kind: ReplicationController
apiVersion: v1
metadata:
  name: spark-worker-controller
  namespace: spark
spec:
  replicas: 1
  selector:
    component: spark-worker
  template:
    metadata:
      labels:
        component: spark-worker
    spec:
      nodeSelector:
        use: spark-worker
      containers:
        - name: spark-worker
          image: bde2020/spark-worker
          ports:
            - containerPort: 8081
