kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: spark-worker
spec:
  serviceName: spark-worker
  replicas: 1
  template:
    metadata:
      labels:
        role: spark-worker
    spec:
      terminationGracePeriodSeconds: 0
      volumes:
        - name: spark-conf
          configMap:
            name: spark-worker-config
            items:
              - key: spark-env.sh
                path: spark-env.sh
              - key: spark-defaults.conf
                path: spark-defaults.conf
              - key: log4j.properties
                path: log4j.properties  
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: role
                  operator: In
                  values:
                    - spark-worker
      containers:
        - name: spark-worker
          image: databench/apache-spark-basic:0.4.1
          command: ["$(SPARK_HOME)/sbin/start-slave.sh","$(CLUSTER_MASTER)"]
          envFrom:
            - configMapRef:
                name: spark-shared-env
          ports:
            - containerPort: 8081
          volumeMounts:
            - name: spark-conf
              mountPath: /usr/share/apache-spark/conf/spark-defaults.conf
              subPath: spark-defaults.conf
            - name: spark-conf
              mountPath: /usr/share/apache-spark/conf/spark-env.sh
              subPath: spark-env.sh
            - name: spark-conf
              mountPath: /usr/share/apache-spark/conf/log4j.properties
              subPath: log4j.properties

