---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-00
  labels:
    app: zookeeper
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-00
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-01
  labels:
    app: zookeeper
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-01
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-02
  labels:
    app: zookeeper
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-02
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-03
  labels:
    app: zookeeper
    app: kafka
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-03
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-04
  labels:
    app: zookeeper
    app: kafka
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-04
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: data-05
  labels:
    app: zookeeper
    app: kafka
    storage: persistent
spec:
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  hostPath:
    path: /export/scratch/kafka/data-05
