apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id=0
    auto.create.topics.enable=true
    group.initial.rebalance.delay.ms=0
    log.dirs=/var/lib/kafka/data/topics
    log.retention.check.interval.ms=300000
    log.retention.hours=-1
    log.segment.bytes=1073741824
    num.io.threads=8
    num.network.threads=3
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    socket.send.buffer.bytes=102400
    transaction.state.log.min.isr=1
    transaction.state.log.replication.factor=1
    zookeeper.connection.timeout.ms=6000
    zookeeper.connect=zookeeper.default.svc.cluster.local:2181
