apiVersion: v1
kind: ConfigMap
metadata:
  name: kafka-config
data:
  server.properties: |
    broker.id=0
    auto.create.topics.enable=true
    group.initial.rebalance.delay.ms=0
    log.dirs=/var/lib/kafka/data/topics
    log.retention.check.interval.ms=300000
    log.retention.hours=-1
    log.segment.bytes=1073741824
    num.io.threads=8
    num.network.threads=3
    num.partitions=1
    num.recovery.threads.per.data.dir=1
    offsets.topic.replication.factor=1
    socket.receive.buffer.bytes=102400
    socket.request.max.bytes=104857600
    socket.send.buffer.bytes=102400
    transaction.state.log.min.isr=1
    transaction.state.log.replication.factor=1
    zookeeper.connection.timeout.ms=6000
    zookeeper.connect=zookeeper.default.svc.cluster.local:2181
  log4j.properties: |
    log4j.additivity.kafka.authorizer.logger=false
    log4j.additivity.kafka.controller=false
    log4j.additivity.kafka.log.LogCleaner=false
    log4j.additivity.kafka.network.RequestChannel$=false
    log4j.additivity.kafka.request.logger=false
    log4j.additivity.state.change.logger=false
    log4j.appender.authorizerAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.authorizerAppender.File=${kafka.logs.dir}/kafka-authorizer.log
    log4j.appender.authorizerAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.authorizerAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.authorizerAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.cleanerAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.cleanerAppender.File=${kafka.logs.dir}/log-cleaner.log
    log4j.appender.cleanerAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.cleanerAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.cleanerAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.controllerAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.controllerAppender.File=${kafka.logs.dir}/controller.log
    log4j.appender.controllerAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.controllerAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.controllerAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.kafkaAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.kafkaAppender.File=${kafka.logs.dir}/server.log
    log4j.appender.kafkaAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.kafkaAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.kafkaAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.requestAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.requestAppender.File=${kafka.logs.dir}/kafka-request.log
    log4j.appender.requestAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.requestAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.requestAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.stateChangeAppender.DatePattern='.'yyyy-MM-dd-HH
    log4j.appender.stateChangeAppender.File=${kafka.logs.dir}/state-change.log
    log4j.appender.stateChangeAppender.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.stateChangeAppender.layout=org.apache.log4j.PatternLayout
    log4j.appender.stateChangeAppender=org.apache.log4j.DailyRollingFileAppender
    log4j.appender.stdout.layout.ConversionPattern=[%d] %p %m (%c)%n
    log4j.appender.stdout.layout=org.apache.log4j.PatternLayout
    log4j.appender.stdout=org.apache.log4j.ConsoleAppender
    log4j.logger.kafka.authorizer.logger=WARN, authorizerAppender
    log4j.logger.kafka.controller=TRACE, controllerAppender
    log4j.logger.kafka=INFO
    log4j.logger.kafka.log.LogCleaner=INFO, cleanerAppender
    log4j.logger.kafka.network.RequestChannel$=WARN, requestAppender
    log4j.logger.kafka.request.logger=WARN, requestAppender
    log4j.logger.org.apache.kafka=INFO
    log4j.logger.org.apache.zookeeper=INFO
    log4j.logger.org.I0Itec.zkclient.ZkClient=INFO
    log4j.logger.state.change.logger=TRACE, stateChangeAppender
    log4j.rootLogger=INFO, stdout, kafkaAppender
