kind: StatefulSet
apiVersion: apps/v1beta1
metadata:
  name: consumer-dev
spec:
  serviceName: consumer-dev
  replicas: 1
  template:
    metadata:
      labels:
        spark-role: app
    spec:
      volumes:
        - name: spark-conf
          configMap:
            name: consumer-dev-config
            items:
              - key: spark-env.sh
                path: spark-env.sh
              - key: spark-defaults.conf
                path: spark-defaults.conf
        - name: spark-data
          hostPath:
            path: /export/scratch/consumer-dev
      nodeSelector:
        role: workload
      containers:
        - name: consumer-dev
          image: databench/apache-spark-basic
          command:
            - sleep
            - 120d
          envFrom:
            - configMapRef:
                name: databench-env
            - configMapRef:
                name: spark-shared-env
          volumeMounts:
            - name: spark-conf
              mountPath: "/usr/share/apache-spark/conf"
            - name: spark-data              
              mountPath: /scratch
              
          
