---
- hosts: master
  gather_facts: no
  user: root
  vars:
    one_month: 2592000 # 60*60*24*30 - 1 month
    services:
      grafana:
        local_port: 3000
        remote_port: 3000
        namespace: kube-system
        label: k8s-app=grafana
        enabled: true
      influxdb:
        local_port: 8086
        remote_port: 8086
        namespace: kube-system
        label: k8s-app=influxdb
        enabled: true
      kafka:
        local_port: 9092
        remote_port: 9092
        namespace: default
        label: role=kafka
        enabled: true
      cassandra:
        local_port: 9042
        remote_port: 9042
        namespace: default
        label: role=cassandra
        enabled: false
      zookeeper:
        local_port: 2888
        remote_port: 2888
        namespace: default
        label: role=zookeeper
        enabled: false
      spark-ui-proxy:
        local_port: XXXX
        remote_port: XXXX
        namespace: default
        label: role=spark-ui-proxy
        enabled: false
    
  tasks:

    - name: " stop kubernetes port-forwarding"
      command: "pkill -9 -f kubectl.+port-forward.+{{item.key}}"
      with_dict: "{{services}}"
      ignore_errors: true
      tags:
        - stop

    - name: "start kubernetes port-forwarding"
      shell:
        kubectl get pods -n {{item.value.namespace}}
        -l {{item.value.label}}
        -o jsonpath='{.items[0].metadata.name}' |
        xargs -I= kubectl port-forward =
        {{item.value.local_port}}:{{item.value.remote_port}}
      async: "{{one_month}}"
      poll: 0
      with_dict: "{{services}}"
      when: item.value.enabled
      tags:
        - start
