---
- hosts: master
  vars:
    scale_0_1: --current-replicas=0 --replicas=1
    scale_1_0: --current-replicas=1 --replicas=0
    telemetry_workload: sleep 10s
    observer: simple-observer
    
  tasks:
    - name: "stop workload pods and observer"
      command: "kubectl scale --replicas=0 statefulset/{{item}}"
      with_items:
        - generators
        - consumers
        - simple-observer
      ignore_errors: True
      tags:
        - stop

    # prompt user for path to archive last run

    - name: "prompt user for archive path   "
      debug:
        msg: NotImplemented
      tags:
        - archive
      when: archive_path is not defined and doArchving is defined

    - name: "archive databench database     "
      debug:
        msg: NotImplemented
      tags:
        - archive
      when: archive_path is defined

    - name: "flush influx databench database"
      command:
        kubectl scale {{item}} deployment/monitoring-influxdb -n kube-system
      with_items:
        - --replicas=0
        - --replicas=1
      tags:
        - flush
  
    - name: "flush kafka topics             "
      command: "kubectl scale {{item}} statefulset/kafka"
      with_items:
        - --replicas=0
        - --replicas=1        
      tags:
        - flush

    - name: "start observer                 "
      command:
        "kubectl scale {{scale_0_1}} statefulset/{{observer}}"
      tags:
        - start
        - start-observer
      
    - name: "start consumers                "
      command:
        "kubectl scale {{scale_0_1}} statefulset/consumers"
      tags:
        - start
        - start-consumers

    - name: "start telemetry                 "
      debug:
        msg: NotImplemented
      tags:
        - start
        - start-telemetry
        

    - name: "start generators                "
      command:
        "kubectl scale {{scale_0_1}} statefulset/{{item}}"
      with_items:
        - generators
      tags:
        - start
        - start-generators
