apiVersion: apps/v1beta1
kind: StatefulSet
metadata:
  name: data-bench-generators
spec:
  serviceName: generators
  replicas: 1
  template:
    metadata:
      labels:
        role: generator
    spec:
      volumes:
        - name: config
          configMap:
            name: generators-config
            items:
              - key: marketstream-config.ini
                path: config.ini
              - key: customervaluation-config.ini
                path: config.ini
      containers:
        - name: marketstream
          image: databench/marketstream-generator
          command: [ "python3", "marketstream.py" ]
          envFrom:
            - configMapRef:
                name: generators-env
          volumeMounts:
            - name: config
              mountPath: /config.ini
              subPath: config.ini
        - name: customervaluation
          image: databench/customervaluation-generator
          command: [ "python3", "customervaluation.py" ]
          envFrom:
            - configMapRef:
                name: generators-env
          volumeMounts:
            - name: config
              mountPath: /config.ini
              subPath: config.ini
