---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: data-bench-consumers
  labels:
    cat: consumers
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: data-bench
        cat: consumer
    spec:
      containers:
        - name: marketstream
          image: databench/marketstream-consumer
        - name: customervaluation
          image: databench/customervaluation-consumer
